/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Component;


import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import java.awt.Font;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * 
 * THIS PROGRAM DISPLAYS THE CURRENT DATE AT THE TOP, MONTH & YEAR OF
 * A GIVEN DATE ABOVE THE CALENDAR PAGE,A CALENDAR PAGE THAT CONTAINS
 * COLUMN HEADERS FOR NAMES OF DAYS IN WEEK & A GRID OF NUMBERS CORRESPONDING 
 * TO THE DAYS IN THE MONTH.THE PROGRAM ALSO DISPLAYS DAY(S) OF THE PREVIOUS & 
 * NEXT MONTH IN LIGHT-GRAY COLOR.UNDER THE CALENDAR PAGE THE CURRENT TIME IS 
 * DISPLAYED.THE PROGRAM ALLOWS THE USER TO NAVIGATE THE CALENDAR BY DISPLAYING
 * A PREVIOUS OR NEXT MONTH.
 *  
 * 
 */

public class AdminCalendar extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
     private final String[] MONTHS = {"January","Febuary","March","April",
                                  "May","June","July","August","September",
                                  "October","November","December"
                                  
                                  };
    private  AdminCalendarPage calenderPage;
    private Calendar  calDate;
    GregorianCalendar greCal;
    private DefaultComboBoxModel<String> yearboxModel;
    public AdminCalendar() {
    	getContentPane().setBackground(new Color(102, 0, 0));
    	setBackground(new Color(102, 0, 0));
        calDate = Calendar.getInstance();
       
        initComponents();
        displayCalendar(0);
        calenderPage.printDate(dateView);     
        dateView.setLayout(null);
        
        lblNewLabel = new JLabel("");
        lblNewLabel.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		
        		dispose();
        	}
        });
        lblNewLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel.setIcon(new ImageIcon("C:\\Users\\jamun\\eclipse-workspace\\HostelManagementSystem\\images\\cancel.png"));
        lblNewLabel.setBounds(947, 0, 48, 41);
        dateView.add(lblNewLabel);
        calenderPage.printTime(clockView); 
        yearboxModel =  (DefaultComboBoxModel<String>) yearCombo.getModel();
        yearboxModel.removeAllElements();
        yearboxModel.addElement(String.valueOf(calDate.get(Calendar.YEAR)));
       initComboYear();
       month.setModel(new DefaultComboBoxModel<>(MONTHS));
       
      // clockPane.add(new ClockPane());
       
    }

 private void initComboYear(){
 
     int x  =  Integer.valueOf(yearboxModel.getSelectedItem().toString());
     yearboxModel.removeAllElements();
 for(int i= x; i >= 1900; --i ){
 yearboxModel.addElement(String.valueOf(i));
}
 
 }   
    
    
    private void displayCalendar(int month){
        
       calDate.add(Calendar.MONTH, month);
       
       int y = calDate.get(Calendar.YEAR);
       int m = calDate.get(Calendar.MONTH);    
       calenderPage =  new AdminCalendarPage(y ,m,topDAte,calendarView);
     if(calendarView.getComponents().length > 0){
       Component com  = calendarView.getComponent(0);
         if(com instanceof  JPanel){
         calendarView.remove(0);
         calendarView.add(calenderPage,0);
         calendarView.revalidate();
      }
         
     }else calendarView.add(calenderPage);
     

    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(Color.LIGHT_GRAY);
        dateView = new javax.swing.JPanel();
        calendarView = new javax.swing.JPanel();
        clockView = new javax.swing.JPanel();
        clockView.setBackground(Color.LIGHT_GRAY);
        jToolBar3 = new javax.swing.JToolBar();
        jToolBar3.setBackground(Color.LIGHT_GRAY);
        jButton2 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jToolBar1.setBackground(Color.LIGHT_GRAY);
        jButton1 = new javax.swing.JButton();
        topDAte = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBackground(Color.LIGHT_GRAY);
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Tahoma", Font.BOLD, 11));
        yearCombo = new javax.swing.JComboBox<>();
        yearCombo.setBackground(Color.LIGHT_GRAY);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.BOLD, 11));
        month = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calendar");
        setResizable(false);
        setSize(new java.awt.Dimension(553, 357));
        setUndecorated(true);

        dateView.setBackground(new java.awt.Color(153, 204, 255));
        dateView.setFont(new java.awt.Font("Arial", 1, 24));

        calendarView.setBackground(new java.awt.Color(213, 220, 238));
        calendarView.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.black), javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)));
        calendarView.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        clockView.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));
        clockView.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clockView.setMinimumSize(new java.awt.Dimension(535, 35));
        clockView.setPreferredSize(new java.awt.Dimension(535, 35));
        clockView.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 2));

        jToolBar3.setBorder(null);
        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/img/Arrows-Left-Round-icon.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton2);

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/img/Arrows-Right-Round-icon.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setFocusable(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        topDAte.setBackground(new java.awt.Color(102, 204, 255));
        topDAte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        topDAte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topDAte.setText("Month");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(51, 51, 51)), "Go To", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel1.setLabelFor(yearCombo);
        jLabel1.setText("Year:");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        yearCombo.setEditable(true);
        yearCombo.setModel(new DefaultComboBoxModel(new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));
        yearCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearComboKeyTyped(evt);
            }
        });

        jLabel2.setText("Month:");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        month.setEditable(true);
        month.setSelectedItem(MONTHS[calDate.get(Calendar.MONTH)]);
        month.setFocusable(false);
        month.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthItemStateChanged(evt);
            }
        });
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("Go");
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel1)
        				.addComponent(jLabel2))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(month, 0, 1, Short.MAX_VALUE)
        				.addComponent(yearCombo, 0, 99, Short.MAX_VALUE)))
        		.addComponent(jButton3, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(30)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(yearCombo, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(month, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jButton3)
        			.addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.linkSize(SwingConstants.VERTICAL, new Component[] {jLabel1, yearCombo, jLabel2, month});
        jPanel2Layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {jLabel1, jLabel2});
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(dateView, GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(jToolBar3, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(topDAte, GroupLayout.PREFERRED_SIZE, 849, GroupLayout.PREFERRED_SIZE)
        			.addGap(55)
        			.addComponent(jToolBar1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        			.addGap(0, 0, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(48)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(clockView, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(calendarView, GroupLayout.PREFERRED_SIZE, 594, GroupLayout.PREFERRED_SIZE)
        					.addGap(68))))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(dateView, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jToolBar3, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(topDAte, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jToolBar1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(94)
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(calendarView, GroupLayout.PREFERRED_SIZE, 435, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(clockView, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        			.addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
        displayCalendar(1);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        displayCalendar(-1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void monthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthItemStateChanged

      

    }//GEN-LAST:event_monthItemStateChanged

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed


       

    }//GEN-LAST:event_monthActionPerformed

    private void yearComboKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearComboKeyTyped
        System.out.println(yearCombo.getSelectedItem());
    }//GEN-LAST:event_yearComboKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
        String yr  = yearCombo.getSelectedItem().toString();
        if(!yr.matches("\\d+") ||yr.matches("-\\d+") || yr.matches("0") ){
        yr = calDate.get(Calendar.YEAR)+"";
        yearCombo.setSelectedItem(yr);
        month.setSelectedIndex(calDate.get(Calendar.MONTH));
        }
        
        int y = Integer.valueOf(yr);
       int m = month.getSelectedIndex();
     
       
       calDate.set(Calendar.YEAR, y);
       calDate.set(Calendar.MONTH, m);
     calenderPage =  new AdminCalendarPage(y ,m,topDAte,calendarView);
     if(calendarView.getComponents().length > 0){
       Component com  = calendarView.getComponent(0);
         if(com instanceof  JPanel){
         calendarView.remove(0);
         calendarView.add(calenderPage,0);
         calendarView.revalidate();
      }
         
     }else calendarView.add(calenderPage);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCalendar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel calendarView;
    private javax.swing.JPanel clockView;
    private javax.swing.JPanel dateView;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JLabel topDAte;
    private javax.swing.JComboBox<String> yearCombo;
    private JLabel lblNewLabel;
    // End of variables declaration//GEN-END:variables
}
